webtalk_init -webtalk_dir C:/Users/c170095/Downloads/Lab 3/Lab 3.sim/sim_1/behav/xsim/xsim.dir/AM_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 17 13:17:29 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210774966_1777502827_210726841_362" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "24326d52-6aca-4815-acb3-13019ada6bda" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "dd6da1a307014f23a9183eff0903bca6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3467 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "3" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "10.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "130 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8588_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2681386680 -regid "210774966_1777502827_210726841_362" -xml C:/Users/c170095/Downloads/Lab 3/Lab 3.sim/sim_1/behav/xsim/xsim.dir/AM_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/c170095/Downloads/Lab 3/Lab 3.sim/sim_1/behav/xsim/xsim.dir/AM_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/c170095/Downloads/Lab 3/Lab 3.sim/sim_1/behav/xsim/xsim.dir/AM_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
